name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: |
            FROM alpine:latest

            RUN apk add --no-cache git neovim ripgrep build-base bash python3 py3-pip \
              && pip3 install --upgrade pip \
              && pip3 install pynvim \
              && git clone https://github.com/HydraVim/HydraVim.git --depth 1 --branch main ~/.config/nvim

            CMD ["nvim"]
          push: true
          tags: diogoss/hydravim:latest
